### PR TITLE
Added Dapple to fish list on index.html; added javascript for dapple'…

### PR DESCRIPTION
**Pull request by Keartroth**
### Changes:
- Added Donkey Dung Sea Cucumber, Dapple, to fish list on index.html.
- Added Dapple's information to javascript on dialog.js for dialog box generation.

### Items to check:
- Check that Dapple shows in fish list.
- Check that Dapple's information shows when clicking the detail button.
- Check that Dapple's modal box closes when pressing the 'close dialog' button.

### CODE REVIEW

**Comment by DanielFuqua** [comment]
👍

**Review by CrystalElseyNSS — APPROVED** [review]
Dapple is a dapper guy! 👍

**Review by DanielFuqua — APPROVED** [review]
👍

**Review by nickglovdev — APPROVED** [review]
Super good! 👍

**Review by CrystalElseyNSS — APPROVED** [review]
Dapple is a dapper gent!

**Review by DanielFuqua — APPROVED** [review]
👍

**Pull request merged**
