### PR TITLE
added Bobby 

### PR DESCRIPTION
**Pull request by DanielFuqua**
### Changes made

Added A fish named Bobby who is a cuttlefish.
Added functionality to Bobby's dialog box.

### How to test

Check to make sure that Bobby was added to the list of fish. 
Click on the "details" button and make sure that the event listener is working and dialog box pops up.
Then see if the close button works.

### CODE REVIEW

**Review by CrystalElseyNSS — APPROVED** [review]
Bobby looks dope AF 👍

**Review by nickglovdev — APPROVED** [review]
Looks like everything is working from your list. 👍

**Review by Keartroth — APPROVED** [review]
👍 Bobby looks great! Ready to merge to master!

**Review by Keartroth — APPROVED** [review]
👍 Looks great!!

**Review by nickglovdev — APPROVED** [review]
👍

**Pull request merged**
