### PR TITLE
Added Simba the lionfish and working dialog button

### PR DESCRIPTION
**Pull request by CrystalElseyNSS**
### Changes
- Added Simba the lionfish to the fish list
- Added dialog button with details for Simba the lionfish

### Testing
- Make sure Simba the lionfish appears in the fish list
- Check that dialog box opens, displays details, and closes

### CODE REVIEW

**Comment by nickglovdev** [comment]
Your close button seems to not be showing. Look into your HTML at your dialog box.

**Comment by DanielFuqua** [comment]
the close button in the dialog is not present

**Review by Keartroth — CHANGES_REQUESTED** [review]
### Comments
- Simba missing close button in index.html; add under list of fish info with correct class.

**Review by DanielFuqua — APPROVED** [review]
👍

**Comment by CrystalElseyNSS** [comment]
### Changes

- Fixed dialog box to include close button

### Testing

- Click on dialog box and make sure close button is present and working

**Comment by CrystalElseyNSS** [comment]
### Changes

Resubmitted with new updated master

### Testing

Please check that both Lips and Simba are present and functional

**Review by Keartroth — APPROVED** [review]
👍

**Pull request merged**
