### PR TITLE
Added Puffer Fish

### PR DESCRIPTION
**Pull request by nickglovdev**
Description
Added the puffer fish Lips to the list of fish and added the dialog box.

Check
If the image of Lips the puffer fish exist.
If the  Lips the puffer fish dialog box opens and closes.

### CODE REVIEW

**Comment by DanielFuqua** [comment]
👍

**Review by Keartroth — CHANGES_REQUESTED** [review]
### Comment:
- Fish details not correct; shows fish details for Dory rather than Lips.
- Fish details needs to be changed in index.html.

**Review by CrystalElseyNSS — APPROVED** [review]
Lips looks luscious! 👍

**Review by DanielFuqua — APPROVED** [review]
👍

**Pull request merged**
